### ISSUE TITLE
Kubernetes Environment

### ISSUE THREAD

**Issue by blaubaer** [engity-com/bifroest#12]
## Is your feature request related to a problem? Please describe.
Similar cases as for the [Docker Environment](11), but plus:
1. I want to be able to access Kubernetes cluster resources from within the cluster itself. I don't want to use `kubectl exec <whatever>` anymore to go into another container (which matches the best for me).
2. I want to use `ssh -D8080 sso@bastion.host` to have a [local SOCKS5 proxy](https://man.openbsd.org/ssh.1#D) to directly access all cluster internal resources from my own computer terminal via `curl` or even with my favorite browser - without the need to forward each target port explicitly with `kubectl port-forward`.
3. I want to have the correct tools already available inside the cluster.
4. I don't want my Kubernetes cluster polluted by other users.
5. I want that this container/POD is disposed (cleaned up) if I do not longer need it, automatically.

## Describe the solution you'd like
Instead of the currently supported local environment, we should provide a Kubernetes environment which will run every Bifröst's session inside an own Kubernetes POD on a defined target cluster.

It should be possible to use different:
1. Environment variables
2. Images
3. Networks
6. Commands
7. Container internal users

**Comment by CiaoOtway** [comment]
see inline comments
