### ISSUE TITLE
[FEATURE] Restrict OPENID after login by user data

### ISSUE THREAD

**Issue by Nathanwoodburn** [engity-com/bifroest#69]
### Is your feature request related to a problem?

This isn't a problem just a nice future feature if you have the time.

### Describe the solution you'd like.

It would be nice to restrict OPENID logins using the user data. For example after the user logs in to OPENID, only allow access if either
- in group `ssh-flowname`
- username `superadmin`

### Describe alternatives you've considered

The alternative is creating separate OPENID client/secrets for each flow to restrict logins on the OPENID server. This is a bit more painful as it requires creating multiple of the clients and keeping track of them all.

**Comment by blaubaer** [comment]
Hi @Nathanwoodburn,

I would assume what you're requesting might be already fulfilled by the `loginAllowed` property. It might be confusing that this property is not part of the authorization, it is part of the [environments](https://bifroest.engity.org/reference/environment/):
1. [Docker](https://bifroest.engity.org/reference/environment/docker/#property-loginAllowed)
2. [Kubernetes](https://bifroest.engity.org/reference/environment/kubernetes/#property-loginAllowed)
3. [Local](https://bifroest.engity.org/reference/environment/local/#linux-property-loginAllowed)
